In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df1 = pd.read_csv("../Data/nutrients/FOOD-DATA-GROUP1.csv")
df2 = pd.read_csv("../Data/nutrients/FOOD-DATA-GROUP2.csv")
df3 = pd.read_csv("../Data/nutrients/FOOD-DATA-GROUP3.csv")
df4 = pd.read_csv("../Data/nutrients/FOOD-DATA-GROUP4.csv")
df5 = pd.read_csv("../Data/nutrients/FOOD-DATA-GROUP5.csv")

In [37]:
#df1,2,3,4,5 Have similar structure
df1.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [38]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551 entries, 0 to 550
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.1          551 non-null    int64
 1   Unnamed: 0            551 non-null    int64
 2   food                  551 non-null    object
 3   Caloric Value         551 non-null    int64
 4   Fat                   551 non-null    float64
 5   Saturated Fats        551 non-null    float64
 6   Monounsaturated Fats  551 non-null    float64
 7   Polyunsaturated Fats  551 non-null    float64
 8   Carbohydrates         551 non-null    float64
 9   Sugars                551 non-null    float64
 10  Protein               551 non-null    float64
 11  Dietary Fiber         551 non-null    float64
 12  Cholesterol           551 non-null    float64
 13  Sodium                551 non-null    float64
 14  Water                 551 non-null    float64
 15  Vitamin A             551 non-null    float64
 16  Vitamin B1            551 non-null    float64
 17  Vitamin B11           551 non-null    float64
 18  Vitamin B12           551 non-null    float64
 19  Vitamin B2            551 non-null    float64
 20  Vitamin B3            551 non-null    float64
 21  Vitamin B5            551 non-null    float64
 22  Vitamin B6            551 non-null    float64
 23  Vitamin C             551 non-null    float64
 24  Vitamin D             551 non-null    float64
 25  Vitamin E             551 non-null    float64
 26  Vitamin K             551 non-null    float64
 27  Calcium               551 non-null    float64
 28  Copper                551 non-null    float64
 29  Iron                  551 non-null    float64
 30  Magnesium             551 non-null    float64
 31  Manganese             551 non-null    float64
 32  Phosphorus            551 non-null    float64
 33  Potassium             551 non-null    float64
 34  Selenium              551 non-null    float64
 35  Zinc                  551 non-null    float64
 36  Nutrition Density     551 non-null    float64
dtypes: float64(33), int64(3), object(1)
memory usage: 159.4+ KB

In [43]:
df=pd.concat([df1,df2,df3,df4,df5],ignore_index=True)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2395 entries, 0 to 2394
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.1          2395 non-null   int64
 1   Unnamed: 0            2395 non-null   int64
 2   food                  2395 non-null   object
 3   Caloric Value         2395 non-null   int64
 4   Fat                   2395 non-null   float64
 5   Saturated Fats        2395 non-null   float64
 6   Monounsaturated Fats  2395 non-null   float64
 7   Polyunsaturated Fats  2395 non-null   float64
 8   Carbohydrates         2395 non-null   float64
 9   Sugars                2395 non-null   float64
 10  Protein               2395 non-null   float64
 11  Dietary Fiber         2395 non-null   float64
 12  Cholesterol           2395 non-null   float64
 13  Sodium                2395 non-null   float64
 14  Water                 2395 non-null   float64
 15  Vitamin A             2395 non-null   float64
 16  Vitamin B1            2395 non-null   float64
 17  Vitamin B11           2395 non-null   float64
 18  Vitamin B12           2395 non-null   float64
 19  Vitamin B2            2395 non-null   float64
 20  Vitamin B3            2395 non-null   float64
 21  Vitamin B5            2395 non-null   float64
 22  Vitamin B6            2395 non-null   float64
 23  Vitamin C             2395 non-null   float64
 24  Vitamin D             2395 non-null   float64
 25  Vitamin E             2395 non-null   float64
 26  Vitamin K             2395 non-null   float64
 27  Calcium               2395 non-null   float64
 28  Copper                2395 non-null   float64
 29  Iron                  2395 non-null   float64
 30  Magnesium             2395 non-null   float64
 31  Manganese             2395 non-null   float64
 32  Phosphorus            2395 non-null   float64
 33  Potassium             2395 non-null   float64
 34  Selenium              2395 non-null   float64
 35  Zinc                  2395 non-null   float64
 36  Nutrition Density     2395 non-null   float64
dtypes: float64(33), int64(3), object(1)
memory usage: 692.4+ KB

In [45]:
df.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [48]:
df=df.drop(columns=['Unnamed: 0.1','Unnamed: 0'])

In [50]:
df.describe()

,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,Cholesterol,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
count,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,...,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000,2395.000000
mean,223.769520,10.176276,3.924917,4.133622,2.152844,18.589021,4.457459,13.400777,2.235790,62.171937,...,52.047728,9.581689,1.853271,34.429792,5.349964,156.236052,303.833939,52.258006,1.579192,106.929006
std,384.728244,29.008915,19.502262,12.939587,7.145738,29.406134,13.339929,32.294246,5.404483,385.352876,...,115.933379,69.912400,5.155650,71.927990,21.005332,333.257099,589.507589,199.257203,4.937509,173.023891
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,44.500000,0.300000,0.064000,0.058000,0.071000,0.500000,0.000000,0.800000,0.000000,0.000000,...,0.600000,0.040000,0.100000,1.500000,0.037000,0.800000,27.750000,0.016000,0.055000,16.876500
50%,117.000000,2.100000,0.500000,0.500000,0.400000,6.800000,0.086000,3.500000,0.200000,0.000000,...,13.900000,0.100000,0.600000,10.400000,0.200000,42.300000,112.300000,0.053000,0.300000,53.840000
75%,258.000000,9.400000,2.700000,3.400000,1.700000,25.050000,3.200000,13.300000,2.200000,26.450000,...,48.250000,0.400000,1.800000,36.950000,0.700000,171.350000,340.500000,0.090000,1.200000,135.074500
max,6077.000000,550.700000,672.000000,291.100000,188.000000,390.200000,291.500000,560.300000,76.500000,10509.000000,...,1283.500000,1890.000000,121.200000,921.600000,451.000000,5490.000000,11336.900000,3308.000000,147.300000,3911.400000

In [53]:
df.shape

(2395, 35)